name: Build and Test

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0

    - name: Restore NuGet Packages (Legacy)
      run: nuget restore ClothesWebNET.sln

    - name: Restore NuGet Packages (Test Project)
      run: msbuild -t:restore ClothesWebNET.Tests\ClothesWebNET.Tests.csproj

    - name: Build Solution
      run: msbuild ClothesWebNET.sln /p:Configuration=Release

    - name: Build Test Project
      run: msbuild ClothesWebNET.Tests\ClothesWebNET.Tests.csproj /p:Configuration=Release

    - name: Debug - List Build Output
      run: Get-ChildItem -Path ClothesWebNET.Tests\bin -Recurse

    - name: Setup VSTest
      uses: darenm/Setup-VSTest@v1

    - name: Run Unit Tests
      run: vstest.console.exe .\ClothesWebNET.Tests\bin\Release\net472\ClothesWebNET.Tests.dll
